### ISSUE TITLE
turtles for Classifications and Correspondences?

### ISSUE THREAD

**Issue by VladimirAlexiev** [FranckCo/Stamina#12]
@FranckCo I'm looking for the turtles for Classifications and Correspondences described in http://semstats.org/2016/challenge/classifications. 
INSEE sent me to this repo (see https://twitter.com/InseeFr/status/833679724111097859) but I cannot find them.

**Comment by cmutel** [comment]
This data is available at the same site, though on a slightly different page: http://semstats.org/2016/challenge/challenge-data.

**Comment by VladimirAlexiev** [comment]
thanks!
